### ISSUE TITLE
unimorph query fails for Finnish

### ISSUE THREAD

**Issue by juditacs** [unimorph/unimorph#2]
Thank you for creating a python package.

This command gives me an exception because Finnish is split into two files `fin.1` and `fin.2`:
(I removed parts of the file paths)

~~~
unimorph inflect --word koira --lang fin

Traceback (most recent call last):
  File "miniconda3/bin/unimorph", line 8, in <module>
    sys.exit(main())
  File "miniconda3/lib/python3.7/site-packages/unimorph.py", line 171, in main
    inflect_word(args.word, lang=args.language, features=args.features), end=""
  File "miniconda3/lib/python3.7/site-packages/unimorph.py", line 89, in inflect_word
    data = load_dataset(lang)
  File "miniconda3/lib/python3.7/site-packages/unimorph.py", line 83, in load_dataset
    language_path, header=None, sep="\t", names=["lemma", "form", "features"]
  File "miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "miniconda3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'data/unimorph/fin/fin' does not exist: b'data/unimorph/fin/fin'
~~~

**Comment by aryamccarthy** [comment]
Great, thanks for the heads-up! Just pushed a new version to PyPI that addresses this.

```
$ unimorph inflect koiravero --lang fin
koiravero	koiraveroa	N;PRT;SG
koiravero	koiraveroihin	N;IN+ALL;PL
koiravero	koiraveroiksi	N;TRANS;PL
koiravero	koiraveroilla	N;AT+ESS;PL
koiravero	koiraveroille	N;AT+ALL;PL
koiravero	koiraveroilta	N;AT+ABL;PL
koiravero	koiraveroina	N;FRML;PL
koiravero	koiraveroineen	N;COM;PL
koiravero	koiraveroin	N;INS;PL
koiravero	koiraveroissa	N;IN+ESS;PL
koiravero	koiraveroista	N;IN+ABL;PL
koiravero	koiraveroitta	N;PRIV;PL
koiravero	koiraveroja	N;PRT;PL
koiravero	koiraverojen	N;GEN;PL
koiravero	koiraveroksi	N;TRANS;SG
koiravero	koiraverolla	N;AT+ESS;SG
koiravero	koiraverolle	N;AT+ALL;SG
koiravero	koiraverolta	N;AT+ABL;SG
koiravero	koiravero	N;ACC;SG
koiravero	koiraverona	N;FRML;SG
koiravero	koiraveron	N;GEN;SG
koiravero	koiravero	N;NOM;SG
koiravero	koiraveroon	N;IN+ALL;SG
koiravero	koiraverossa	N;IN+ESS;SG
koiravero	koiraverosta	N;IN+ABL;SG
koiravero	koiraverot	N;ACC;PL
koiravero	koiraverot	N;NOM;PL
koiravero	koiraverotta	N;PRIV;SG
```
